"""empty message

Revision ID: 142bbc969bfb
Revises: fb071e86aa78
Create Date: 2022-12-18 01:12:02.920345

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '142bbc969bfb'
down_revision = 'fb071e86aa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('state', sa.PickleType(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('game_room', sa.Column('bot_state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_room', 'bot_state', ['bot_state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_room', type_='foreignkey')
    op.drop_column('game_room', 'bot_state_id')
    op.drop_table('bot_state')
    # ### end Alembic commands ###
