"""empty message

Revision ID: 3e357fa1a91d
Revises: 8d1e6431f900
Create Date: 2022-09-06 11:08:37.693492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e357fa1a91d'
down_revision = '8d1e6431f900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_email', sa.String(length=50)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_email')
    # ### end Alembic commands ###
