"""empty message

Revision ID: 656198ec19a8
Revises: fafa14a2a943
Create Date: 2024-02-19 20:38:04.797937

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '656198ec19a8'
down_revision = 'fafa14a2a943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
