"""empty message

Revision ID: 826100105302
Revises: 656198ec19a8
Create Date: 2024-02-20 17:02:14.427090

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '826100105302'
down_revision = '656198ec19a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.alter_column('pwd',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=256),
                              existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwd',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.String(length=256),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwd',
                              existing_type=sa.String(length=256),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)

    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.alter_column('pwd',
                              existing_type=sa.String(length=256),
                              type_=sa.VARCHAR(length=50),
                              existing_nullable=False)

    # ### end Alembic commands ###
