"""empty message

Revision ID: 8d1e6431f900
Revises: f230cda71ccc
Create Date: 2022-07-28 15:27:46.145894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1e6431f900'
down_revision = 'f230cda71ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_room', 'game_seed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_room', sa.Column('game_seed', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
