"""empty message

Revision ID: fafa14a2a943
Revises: 47f13b2316c7
Create Date: 2024-02-19 20:09:28.587349

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fafa14a2a943'
down_revision = '47f13b2316c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_state',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('state', sa.PickleType(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_state'))
                    )
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_room_game_state_id_game_state'), 'game_state',
                                    ['game_state_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_user_name'), ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_user_name'), type_='unique')

    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_room_game_state_id_game_state'), type_='foreignkey')
        batch_op.drop_column('game_state_id')

    op.drop_table('game_state')
    # ### end Alembic commands ###
