"""empty message

Revision ID: fb071e86aa78
Revises: 3e357fa1a91d
Create Date: 2022-09-08 05:25:10.973785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb071e86aa78'
down_revision = '3e357fa1a91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_email_verified')
    # ### end Alembic commands ###
